entwine build -i /vol_c/rem-srer/SRER_Sept_2019_products/22_6/22_6_highdensity_ground.las -o /vol_b/rem-srer/ept/may/22_6 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_products/22_5_products/22-5_highdensity_ground.las -o /vol_b/rem-srer/ept/may/22-5 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_products/22_5_products/22-5_highdensity_ground2.las -o /vol_b/rem-srer/ept/may/22-5 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_products/1a_g2_repeat_products/1a_g2_ultra.las -o /vol_b/rem-srer/ept/may/1a_g2_ultra -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_products/1a_g2_repeat_products/1a_g2_high.las -o /vol_b/rem-srer/ept/may/1a_g2_high -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_products/35b_u2_products/35b_u2_highdensity_ground.las -o /vol_b/rem-srer/ept/may/35b_u2 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_products/35b_u2_products/ultra_cloud.las -o /vol_b/rem-srer/ept/may/ultra_cloud -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_products/35b_u2_products/ground_color.las -o /vol_b/rem-srer/ept/may/ground_color -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_products/35b_u2_products/35b_u2_highdensity_ground2.las -o /vol_b/rem-srer/ept/may/35b_u2 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_products/8_g2_products/8-g2_ground.las -o /vol_b/rem-srer/ept/may/8-g2_ground -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_products/35b_u2_repeat_products/35b_u2_repeat2_highdensity.las -o /vol_b/rem-srer/ept/may/35b_u2_repeat2 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/21_7_pointcloud/21_7_highdensity.las -o /vol_b/rem-srer/ept/may/21_7 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/6a_3_pointcloud/6a_3_highdensity.las -o /vol_b/rem-srer/ept/may/6a_3 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/6_g2_pointcloud/6_g2_highdensity.las -o /vol_b/rem-srer/ept/may/6_g2 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/40_g1_pointcloud/40_g1_highdensity.las -o /vol_b/rem-srer/ept/may/40_g1 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/8_g2_pointcloud/8_g2_highdensity.las -o /vol_b/rem-srer/ept/may/8_g2 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/15_g2_pointcloud/15_2_highdensity.las -o /vol_b/rem-srer/ept/may/15_2 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/22_9_pointcloud/22_9_highdensity.las -o /vol_b/rem-srer/ept/may/22_9 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/8_4_pointcloud/8_4_highdensity.las -o /vol_b/rem-srer/ept/may/8_4 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/22_2_pointcloud/22_2_highdensity.las -o /vol_b/rem-srer/ept/may/22_2 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/2n_10w_pointcloud/2n_10w_highdensity.las -o /vol_b/rem-srer/ept/may/2n_10w -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/8_2_pointcloud/8_2_highdensity.las -o /vol_b/rem-srer/ept/may/8_2 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/21_9_pointcloud/21_9_highdensity.las -o /vol_b/rem-srer/ept/may/21_9 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/1a_u6_pointcloud/1a_u6_highdensity.las -o /vol_b/rem-srer/ept/may/1a_u6 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/5_g1_pointcloud/5_g1_highdensity.las -o /vol_b/rem-srer/ept/may/5_g1 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/41_g2_pointcloud/41_g2_highdensity.las -o /vol_b/rem-srer/ept/may/41_g2 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/6a_36_pointcloud/6a_36_highdensity.las -o /vol_b/rem-srer/ept/may/6a_36 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/6a_20_pointcloud/6a_20_highdensity.las -o /vol_b/rem-srer/ept/may/6a_20 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/22_5_pointcloud/22_5_highdensity.las -o /vol_b/rem-srer/ept/may/22_5 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/8_5_pointcloud/8_5_highdensity.las -o /vol_b/rem-srer/ept/may/8_5 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/6b_3w_pointcloud/6b_3w_highdensity.las -o /vol_b/rem-srer/ept/may/6b_3w -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/6b_56_pointcloud/6b_56_highdensity.las -o /vol_b/rem-srer/ept/may/6b_56 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/35b_u2_pointcloud/35b_u2_highdensity.las -o /vol_b/rem-srer/ept/may/35b_u2 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/22_1_pointcloud/22_1_highdensity.las -o /vol_b/rem-srer/ept/may/22_1 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/6a_15_pointcloud/6a_15_highdensity.las -o /vol_b/rem-srer/ept/may/6a_15 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/21_5_pointcloud/21_5_highdensity.las -o /vol_b/rem-srer/ept/may/21_5 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/4_g2_pointcloud/4_g2_highdensity.las -o /vol_b/rem-srer/ept/may/4_g2 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/6a_42_pointcloud/6a_42_highdensity.las -o /vol_b/rem-srer/ept/may/6a_42 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/1a_g2_pointcloud/1a_g2_highdensity.las -o /vol_b/rem-srer/ept/may/1a_g2 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/42_g2_pointcloud/42_g2_highdensity.las -o /vol_b/rem-srer/ept/may/42_g2 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/21_2_pointcloud/21_2_highdensity.las -o /vol_b/rem-srer/ept/may/21_2 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/9_g1_pointcloud/9_g1_highdensity.las -o /vol_b/rem-srer/ept/may/9_g1 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/2s_9_pointcloud/2s_9_highdensity.las -o /vol_b/rem-srer/ept/may/2s_9 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/28_g1_pointcloud/28_g1_highdensity.las -o /vol_b/rem-srer/ept/may/28_g1 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/2s_6_pointcloud/2s_6_highdensity.las -o /vol_b/rem-srer/ept/may/2s_6 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/6a_39_pointcloud/6a_39_highdensity.las -o /vol_b/rem-srer/ept/may/6a_39 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/6b_60_pointcloud/6b_60_highdensity.las -o /vol_b/rem-srer/ept/may/6b_60 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/21_8_pointcloud/21_8_highdensity.las -o /vol_b/rem-srer/ept/may/21_8 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/22_6_pointcloud/22_6_highdensity.las -o /vol_b/rem-srer/ept/may/22_6 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/6a_1_pointcloud/6a_1_highdensity.las -o /vol_b/rem-srer/ept/may/6a_1 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/2s_2_pointcloud/2s_2_highdensity.las -o /vol_b/rem-srer/ept/may/2s_2 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/22_3_pointcloud/22_3_highdensity.las -o /vol_b/rem-srer/ept/may/22_3 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/8_7_pointcloud/8_7_highdensity.las -o /vol_b/rem-srer/ept/may/8_7 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/22_g1_pointcloud/22_g1_highdensity.las -o /vol_b/rem-srer/ept/may/22_g1 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/6a_16_pointcloud/6a_16_highdensity.las -o /vol_b/rem-srer/ept/may/6a_16 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/6b_54_pointcloud/6b_54_highdensity.las -o /vol_b/rem-srer/ept/may/6b_54 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/35a_u1_pointcloud/35a_u1_highdensity.las -o /vol_b/rem-srer/ept/may/35a_u1 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/21_6_pointcloud/21_6_highdensity.las -o /vol_b/rem-srer/ept/may/21_6 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/2s_1_pointcloud/2s_1_highdensity.las -o /vol_b/rem-srer/ept/may/2s_1 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/42_u1_pointcloud/42_u1_highdensity.las -o /vol_b/rem-srer/ept/may/42_u1 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/23_g1_pointcloud/23_g1_highdensity.las -o /vol_b/rem-srer/ept/may/23_g1 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/21_3_pointcloud/21_3_highdensity.las -o /vol_b/rem-srer/ept/may/21_3 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/2b_u1_pointcloud/2b_u1_highdensity.las -o /vol_b/rem-srer/ept/may/2b_u1 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_May_2019_pointclouds/2n_1w_pointcloud/2n_1w_highdensity.las -o /vol_b/rem-srer/ept/may/2n-t 15 _1w 

entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/21_7_pointcloud/21_7_highdensity.las -o /vol_b/rem-srer/ept/sept/21_7 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/6a_3_pointcloud/6a_3_highdensity.las -o /vol_b/rem-srer/ept/sept/6a_3 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/6_g2_pointcloud/6_g2_highdensity.las -o /vol_b/rem-srer/ept/sept/6_g2 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/40_g1_pointcloud/40_g1_highdensity.las -o /vol_b/rem-srer/ept/sept/40_g1 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/8_g2_pointcloud/8_g2_highdensity.las -o /vol_b/rem-srer/ept/sept/8_g2 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/15_g2_pointcloud/15_g2_highdensity.las -o /vol_b/rem-srer/ept/sept/15_g2 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/22_9_pointcloud/22_9_highdensity.las -o /vol_b/rem-srer/ept/sept/22_9 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/8_4_pointcloud/8_4_highdensity.las -o /vol_b/rem-srer/ept/sept/8_4 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/22_2_pointcloud/22_2_highdensity.las -o /vol_b/rem-srer/ept/sept/22_2 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/2n_10w_pointcloud/2n_10w_highdensity.las -o /vol_b/rem-srer/ept/sept/2n_10w -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/8_2_pointcloud/8_2_highdensity.las -o /vol_b/rem-srer/ept/sept/8_2 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/21_9_pointcloud/21_9_highdensity.las -o /vol_b/rem-srer/ept/sept/21_9 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/1a_u6_pointcloud/1a_u6_highdensity.las -o /vol_b/rem-srer/ept/sept/1a_u6 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/5_g1_pointcloud/5_g1_highdensity.las -o /vol_b/rem-srer/ept/sept/5_g1 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/41_g2_pointcloud/41_g2_highdensity.las -o /vol_b/rem-srer/ept/sept/41_g2 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/6a_36_pointcloud/6a_36_highdensity.las -o /vol_b/rem-srer/ept/sept/6a_36 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/6a_20_pointcloud/6a_20_highdensity.las -o /vol_b/rem-srer/ept/sept/6a_20 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/22_5_pointcloud/22_5_highdensity.las -o /vol_b/rem-srer/ept/sept/22_5 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/8_5_pointcloud/8_5_highdensity.las -o /vol_b/rem-srer/ept/sept/8_5 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/6b_3w_pointcloud/6b_3w_highdensity.las -o /vol_b/rem-srer/ept/sept/6b_3w -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/6b_56_pointcloud/6b_56_highdensity.las -o /vol_b/rem-srer/ept/sept/6b_56 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/35b_u2_pointcloud/35b_u2_highdensity.las -o /vol_b/rem-srer/ept/sept/35b_u2 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/22_1_pointcloud/22_1_highdensity.las -o /vol_b/rem-srer/ept/sept/22_1 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/6a_15_pointcloud/6a_15_highdensity.las -o /vol_b/rem-srer/ept/sept/6a_15 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/21_5_pointcloud/21_5_highdensity.las -o /vol_b/rem-srer/ept/sept/21_5 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/4_g2_pointcloud/4_g2_highdensity.las -o /vol_b/rem-srer/ept/sept/4_g2 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/6a_42_pointcloud/6a_42_highdensity.las -o /vol_b/rem-srer/ept/sept/6a_42 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/1a_g2_pointcloud/1a_g2_highdensity.las -o /vol_b/rem-srer/ept/sept/1a_g2 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/42_g2_pointcloud/42_g2_highdensity.las -o /vol_b/rem-srer/ept/sept/42_g2 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/21_2_pointcloud/21_2_highdensity.las -o /vol_b/rem-srer/ept/sept/21_2 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/9_g1_pointcloud/9_g1_highdensity.las -o /vol_b/rem-srer/ept/sept/9_g1 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/2s_9_pointcloud/2s_9_highdensity.las -o /vol_b/rem-srer/ept/sept/2s_9 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/28_g1_pointcloud/28_g1_highdensity.las -o /vol_b/rem-srer/ept/sept/28_g1 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/2s_6_pointcloud/2s_6_highdensity.las -o /vol_b/rem-srer/ept/sept/2s_6 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/6a_39_pointcloud/6a_39_highdensity.las -o /vol_b/rem-srer/ept/sept/6a_39 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/6b_60_pointcloud/6b_60_highdensity.las -o /vol_b/rem-srer/ept/sept/6b_60 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/21_8_pointcloud/21_8_highdensity.las -o /vol_b/rem-srer/ept/sept/21_8 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/22_6_pointcloud/22_6_highdensity.las -o /vol_b/rem-srer/ept/sept/22_6 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/6a_1_pointcloud/6a_1_highdensity.las -o /vol_b/rem-srer/ept/sept/6a_1 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/2s_2_pointcloud/2s_2_highdensity.las -o /vol_b/rem-srer/ept/sept/2s_2 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/22_3_pointcloud/22_3_highdensity.las -o /vol_b/rem-srer/ept/sept/22_3 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/8_7_pointcloud/8_7_highdensity.las -o /vol_b/rem-srer/ept/sept/8_7 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/22_g1_pointcloud/22_g1_highdensity.las -o /vol_b/rem-srer/ept/sept/22_g1 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/6a_16_pointcloud/6a_16_highdensity.las -o /vol_b/rem-srer/ept/sept/6a_16 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/6b_54_pointcloud/6b_54_highdensity.las -o /vol_b/rem-srer/ept/sept/6b_54 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/35a_u1_pointcloud/35a_u1_highdensity.las -o /vol_b/rem-srer/ept/sept/35a_u1 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/21_6_pointcloud/21_6_highdensity.las -o /vol_b/rem-srer/ept/sept/21_6 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/2s_1_pointcloud/2s_1_highdensity.las -o /vol_b/rem-srer/ept/sept/2s_1 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/42_u1_pointcloud/42_u1_highdensity.las -o /vol_b/rem-srer/ept/sept/42_u1 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/23_g1_pointcloud/23_g1_highdensity.las -o /vol_b/rem-srer/ept/sept/23_g1 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/21_3_pointcloud/21_3_highdensity.las -o /vol_b/rem-srer/ept/sept/21_3 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/2b_u1_pointcloud/2b_u1_highdensity.las -o /vol_b/rem-srer/ept/sept/2b_u1 -t 15 && \
entwine build -i /vol_c/rem-srer/SRER_Sept_2019_pointclouds/2n_1w_pointcloud/2n_1w_highdensity.las -o /vol_b/rem-srer/ept/sept/2n_1w -t 15 
